FROM node:20.10.0

RUN apt update -y;
RUN apt upgrade -y;

# vscode install
RUN {\
  mkdir -p /root/vscode; \
  cd /root/vscode; \
  curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output /root/vscode/vscode_cli.tar.gz;\
  tar xvf vscode_cli.tar.gz;\
  rm vscode_cli.tar.gz;\
};

# install git
RUN apt install git -y;

# install vim
RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
RUN apt install vim -y;


# next-doc pull
RUN {\
  git clone https://github.com/d3v-friends/next-docs /root/next-docs; \
  npm i -g pnpm; \
  cd /root/next-docs; \
  pnpm install; \
};

# next build
WORKDIR $HOME/next-docs

RUN {\
  cd /root/next-docs; \
  pnpm run build; \
}

ENTRYPOINT [ "pnpm", "run", "start" ]
