FROM node:20.10.0

RUN apt update -y;
RUN apt upgrade -y;

# vscode install
RUN {\
  mkdir -p /root/vscode; \
  cd /root/vscode; \
  curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output /root/vscode/vscode_cli.tar.gz;\
  tar xvf vscode_cli.tar.gz;\
  rm vscode_cli.tar.gz;\
};

# install oh-my-bash
RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

# install tools
RUN apt install git -y;
RUN apt install vim -y;

# next-doc pull
COPY ./docker/create/create_env.sh /root/script/create_env.sh
RUN {\
  git clone https://github.com/d3v-friends/next-docs /root/next-docs; \
  sh /root/script/create_env.sh || {echo "fail env"; exit 1;} \
  npm i -g pnpm; \
  cd /root/next-docs; \
  pnpm install; \
  pnpm run build; \
};

# next build
WORKDIR /root/next-docs

CMD ["pnpm", "run", "start"]

