version: "3.8"

services:
  next-docs:
    image: docker.stdlib.in/next-docs:latest
    container_name: next-docs
    ports:
      - "3000:3000"
    volumes:
      - "$HOME/next-docs/content:/root/content"
      - "$HOME/next-docs/config:/root/config"
      - "$HOME/next-docs/.env.production:/root/next-docs/.env.production"
    networks:
      - inner
    restart: always
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m

networks:
  inner:
    driver: bridge
