version: "3.8"

services:
  next-docs:
    image: docker.stdlib.in/next-docs:latest
    container_name: next-docs
    ports:
      - "10000:3000"
    networks:
      - inner
    restart: always
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m

networks:
  inner:
    driver: bridge
